### ISSUE TITLE
Plan and Submit a LFN D&TF Session for CNTI (Co-located with ONEs)

### ISSUE THREAD

**Issue by Smitholi67** [lfn-cnti/cnti#15]
Details for upcoming D&TF can be viewed here:  https://wiki.lfnetworking.org/pages/viewpage.action?pageId=116719912

**Comment by lixuna** [comment]
CNTI - related session proposals:

- [2024-05 - CNTI: CNF-Testsuite Usage Introduction and Certification Demo - LF Networking - LF Networking Confluence](https://wiki.lfnetworking.org/display/LN/2024-05+-+CNTI%3A+CNF-Testsuite+Usage+Introduction+and+Certification+Demo)
- [2024-05 - CNTI: CNF-Testsuite for Contributors and Advanced Users - LF Networking - LF Networking Confluence](https://wiki.lfnetworking.org/display/LN/2024-05+-+CNTI%3A+CNF-Testsuite+for+Contributors+and+Advanced+Users)

**Comment by lixuna** [comment]
D&TF Schedule has been released https://teamup.com/ksgw6qzqcmg9zbzsfq 
- 1:15-2:15pm - CNTI: CNF-Test suite for Contributors and Advanced Users
- 2:15-3:15pm - CNTI: CNF-Test suite Usage Introduction and Certification Demo

**Comment by lixuna** [comment]
Dry run of presentations planned for next week. Comment here to express interest in collaborating and giving feedback

**Comment by lixuna** [comment]
+1 happy to help, Lucina

**Comment by lixuna** [comment]
Intro https://wiki.lfnetworking.org/display/LN/2024-05+-+CNTI%3A+CNF-Testsuite+Usage+Introduction+and+Certification+Demo

Deep Dive https://wiki.lfnetworking.org/display/LN/2024-05+-+CNTI%3A+CNF-Testsuite+for+Contributors+and+Advanced+Users?preview=/124617320/129040450/DTF2024-cnti-contributors.pdf
