### ISSUE TITLE
[Volunteer] Staffing the CNTi booth at ONE Summit

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/cnti#21]
**Describe the action item:**
- LFN booth area will consist of three kiosks/mini booths, one of which will be dedicated to CNTI
- Volunteer to be at the CNTi booth, to staff the area and address questions about the CNTi program

**Tasks:**
- express your interest/availability in being present at the ONE Summit's CNTi booth by commenting in this issue 
- coordinate with Jill, LFN on the volunteer hours needed and your hours of availability

**Comment by Smitholi67** [comment]
I will attend ONEs and am willing to staff the CNTi booth.  I will be available Mon, Tue, and AM on Wed.

**Comment by martin-mat** [comment]
I will attend ONE as well and willing to take some booth shifts.
