### ISSUE TITLE
Modify CNTi Landing Page

### ISSUE THREAD

**Issue by Smitholi67** [lfn-cnti/cnti#26]
The CNTi landing page currently has instructions for getting certified.  The CNTi Certification is however not approved.  Suggestions are:

1)  Remove all references to getting certified OR
2) Add Beta to the landing page section for Certification.

**Comment by Smitholi67** [comment]
Proposed changes:  https://docs.google.com/document/d/1lF3rR3z39B0troqducYxd0vMT8WE9hvFWC3OCphc760/edit?usp=sharing

**Comment by Smitholi67** [comment]
@lixuna - Can you kindly review before I send over to Jill?

**Comment by lixuna** [comment]
@Smitholi67 my preference would be to keep the instructions and add Beta. Keeping the instructions allows interested parties to understand the self-certification process.

I reviewed and added suggestions to the draft.

**Comment by lixuna** [comment]
Update:CNTi Landing Page Update Request sent by Olivier Smith on Wed, May 8, 10:49 AM

**Comment by lixuna** [comment]
QA: Beta was added 

<img width="1073" alt="Screenshot 2024-05-16 at 11 56 51 AM" src="https://github.com/lfn-cnti/cnti/assets/11701267/a9c8d1e3-3791-400b-836e-ca527d79af6f">
