### ISSUE TITLE
Prepare Blog Post to Announce CNTi as LFN Sandbox Project

### ISSUE THREAD

**Issue by Smitholi67** [lfn-cnti/cnti#31]
Jill Lovato will draft an outline for a CNTi Blogpost.  The goal is to publish during the week commencing July 22, 2024.

**Comment by Smitholi67** [comment]
Draft of the blog post is here: https://docs.google.com/document/d/1w0UfLazrbXkcQ2GmDxfMWwS7ThvXr-zPio1qMRFe4n4/edit?usp=sharing

Add feedback/comments by Friday July 19, 2024.

**Comment by rich-l** [comment]
Looks good. One minor suggestion. Change
"The integration from an initiative to a project..."
to
" The evolution from an initiative to a project...? or "The progression from an initiative to a project..."

**Comment by martin-mat** [comment]
lgtm 👍
