### ISSUE TITLE
Reduce CNTi's slack channels to just one, 'cnti'

### ISSUE THREAD

**Issue by martin-mat** [lfn-cnti/cnti#32]
As per decision by TSC on CNTi Governance call on 2024-07-11, reduce slack CNTi's channels from 6 to just one, 'cnti'.

Current CNTi channels:
- cnti-bestpractices
- cnti-certification
- cnti-general
- cnti-testbed
- cnti-testcatalog-testsuite
- cnti-testsuite-dev

Target CNTi channel:
- cnti

Additional aspects to be considered:
- choose best mechanism to do that considering keeping current audience. Seeing number of subscribed members, 'cnti-testsuite-dev' has the most members (26), so perhaps rename this one to 'cnti' and obsolete remaining 5 channels.
- before removing old channels, do proper communication (cnti maillist, messages on old channels) and give reasonable time to subscribers of old channels to move.

**Comment by martin-mat** [comment]
I propose following steps:
1. rename "cnti-testsuite-dev" to "cnti" (cn be done now)
2. post an announcement about slack channel reduction to all current channels (can be done now)
3. delete all "cnti-*" channels except "cnti" (after 1 week after 1./2. is done)

**Comment by lilluzzi** [comment]
Steps 1, 2, 3 are completed
