### ISSUE TITLE
Discuss with Sylva project if they are interested in a Demo session of the CNTi Test Suite

### ISSUE THREAD

**Issue by Smitholi67** [lfn-cnti/cnti#37]
We are thinking to help Sylva by providing an opportunity to demo the CNTi Test Suite.  On 1/24/2024 Martin offered Sylva and they have said it would be of interest in the coming weeks.

**Comment by martin-mat** [comment]
@kosstennbl to conduct cnti testsuite demo on Sylva validatin call on Nov 14
